
@host_url= http://127.0.0.1:8080
@url = {{host_url}}/api/sender
@jwt_token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDIxMTIyNzAsInRva2VuIjoiTVMxQlZWSlRUa0pSVmt0RFIwbFBVRVZYVEUxS1JFaGFWRmt0TVRjd01qRXhNakkzTUEiLCJkYXRhIjp7ImxvZ2luX2RhdGEiOnsiY2hhbmdlX3RpbWUiOjE3MDE4NDUxMTksImlkIjoxLCJzdGF0dXMiOjEsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoiYWFhYWEifSwibG9naW5fdGltZSI6MTcwMjAyNTg3MCwibG9naW5fdHlwZSI6Im5hbWUiLCJ0aW1lX291dCI6MTcwMjExMjI3MCwidXNlcl9pZCI6MSwidXNlcl9uaWNrbmFtZSI6ImFkbWluIiwidXNlcl9wYXNzd29yZF9pZCI6MX19.54NB-KfRYhuPllfmLchlTtx-Xe-SKgBStNnfCAwDu1E

###### rbac ########


### 添加短信配置
POST {{url}}/smser/config_add
Authorization: {{jwt_token}}

{
    "app_id": 1,
    "priority": 1,
    "config_type": 3,
    "config_data":"xxx"
}


### 删除短信配置
POST {{url}}/smser/config_del
Authorization: {{jwt_token}}

{
   "config_id":1
}

### 短信配置列表
POST {{url}}/smser/config_list
Authorization: {{jwt_token}}

{
   "app_id":1
}

### 阿里短信配置列表
POST {{url}}/smser/ali_config_list
Authorization: {{jwt_token}}

{
   "id":null
   "full_data":true
}


###  阿里短信配置添加
POST {{url}}/smser/ali_config_add
Authorization: {{jwt_token}}

{
    "name": "bbbb",
    "access_id": "ssss",
    "access_secret":"cccc"
}


###  阿里短信配置删除
POST {{url}}/smser/ali_config_del
Authorization: {{jwt_token}}

{
    "id":1,
}



###  阿里短信配置编辑
POST {{url}}/smser/ali_config_edit
Authorization: {{jwt_token}}

{
    "id": 29,
    "name": "faadsf",
    "access_id": "adfad",
    "access_secret":"asdfa"
}


###  阿里短信配置关联短信发送
POST {{url}}/smser/ali_app_config_add
Authorization: {{jwt_token}}

{
    "app_id": 1,
    "ali_config_id":29,
    "tpl_id": "adfad",
    "aliyun_sms_tpl": "adfad",
    "aliyun_sign_name": "adfad"
}



### 短信配置关联删除
POST {{url}}/smser/tpl_config_del
Authorization: {{jwt_token}}

{
    "app_config_id": 29
}

### 短信配置关联列表
POST {{url}}/smser/tpl_config_list
Authorization: {{jwt_token}}

{
    // "id": 29,
    // "user_id": 29,
    // "app_id": 29,
    // "tpl": 29
}


###  设置回调地址
POST {{url}}/smser/notify_set_config
Authorization: {{jwt_token}}

{
    "url": "http://ssss.com",
    "app_id": 2
}


### 获取回调地址
POST {{url}}/smser/notify_get_config
Authorization: {{jwt_token}}

{}




### 重置KEY
POST {{host_url}}/notify/sms/1/dsdfsdf
Content-Type: application/json

 [{"send_time" : "2017-08-30 00:00:00","report_time" : "2017-08-30 00:00:00","success" : true,"err_msg" : "用户接收成功","err_code" : "DELIVERED","phone_number" : "18612345678","sms_size" : "1","biz_id" : "932702304080415357^0","out_id" : "1184585343"}]

