
@host_url= http://175.178.90.181
@app_url = {{host_url}}/api/docs
@jwt_token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODYxMzE0ODUsInRva2VuIjoiTVMxU1RsRkhWa3BEUlZWWlJFSmFXRkJVU0VGTlQwbFhVMHN0TVRZNE5qRXpNVFE0TlEiLCJkYXRhIjp7ImxvZ2luX2RhdGEiOnsiY2hhbmdlX3RpbWUiOjE2ODQyMzM3NTQsImlkIjoxLCJzdGF0dXMiOjEsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoiYWFhYWEifSwibG9naW5fdGltZSI6MTY4NjA0NTA4NSwibG9naW5fdHlwZSI6Im5hbWUiLCJ0aW1lX291dCI6MTY4NjEzMTQ4NSwidXNlcl9pZCI6MSwidXNlcl9uaWNrbmFtZSI6Iua1i-ivleeUqOaIty3lt7LlvIDmiYDmnInmnYPpmZAiLCJ1c2VyX3Bhc3N3b3JkX2lkIjo0MH19.4jfUhN5kXX_Ay-_Hog6Uvyqq7aXkpFCrzli8ONaqONw

### git add
POST {{app_url}}/setting/git_add
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "name":"ces" ,
    "url": "https://gitee.com/shan_liu/test111111",
    "max_try": 1
}

### git edit
POST {{app_url}}/setting/git_edit
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "id":3,
   "name":"ces" ,
    "url": "https://gitee.com/shan_liu/test111111",
    "max_try": 1
}
### git del
POST {{app_url}}/setting/git_del
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "id":2
}
### git list
POST {{app_url}}/setting/git_list
Authorization: {{jwt_token}}
Content-Type: application/json

{
   
}


### git detail
POST {{app_url}}/setting/git_detail
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "url":"https://gitee.com/shan_liu/test111111"
}


### tag add
POST {{app_url}}/setting/tag_add
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "git_id":3,
   "tag":"0000",
   "build_version":"6b1e892c3dd30d189afeeff0ce72fcb512c526c1",
   "clear_rule":["\\.js$"]
}


### tag list
POST {{app_url}}/setting/tag_list
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "count_num":true
}

### tag del
POST {{app_url}}/setting/tag_del
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "tag_id":1
}

### tag dir
POST {{app_url}}/setting/tag_dir
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "tag_id":4,
   "prefix":""
}


### tag dir
POST {{app_url}}/setting/tag_status
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "status":2,
    "tag_id":4
}

### tag dir
POST {{app_url}}/setting/tag_file_data
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "tag_id":4,
   "file_path":"menu.json"
}

### menu add
POST {{app_url}}/setting/menu_add
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "tag_id":4,
   "menu_path":"menu1.json"
}

### menu list
POST {{app_url}}/setting/menu_del
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "menu_id":2
}


### menu del
POST {{app_url}}/setting/menu_list
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "tag_id":4
}

### menu 
POST {{app_url}}/read/menu
Authorization: {{jwt_token}}
Content-Type: application/json

{
  
}

### menu  md
POST {{app_url}}/read/md
Authorization: {{jwt_token}}
Content-Type: application/json

{
   "menu_id":3,
   "url":"README.md"
}