
@host_url= http://127.0.0.1:8080
@user_url = {{host_url}}/api/user
@jwt_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidG9rZW4iOiJOaTFRVVVGTFdFOUVRMVZDUlZwSFYxSk9Ta3hOU1ZSSVZsTXRNVFkzTkRrNU16YzVPUSIsImV4cCI6MTUxNjIzOTAyMjExfQ.kpImEozCMcmGgZs0ngjvAXB-Boq0PEV9sutiAvFSwZg




# jwt 字段
#  pub exp: i64,
#  pub token: String,


POST {{user_url}}/external/bind_check
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "login_type": "wechat",
    "login_state":"343444eee"
}


### oauth bind
POST {{user_url}}/external/bind_url
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "login_type": "wechat",
    "login_state":"343444eee",
    "callback_url":"http://www.lsys.cc/ui/#/user/info/oauth"
}


### oauth list
POST {{user_url}}/external/list_data
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "oauth_type": [1]
}



### oauth delete
POST {{user_url}}/external/delete
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "ext_id": 8
}

