
@host_url= http://127.0.0.1:8080
@user_url = {{host_url}}/api/user
@jwt_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidG9rZW4iOiJOaTFRVEU1VFJGcERUMUZXUmtsVVdFZENWVmRMVWxsRlRVb3RNVFkyTnpFNE5Ua3dPQT09IiwiZXhwIjoxNTE2MjM5MDIyMX0.qYtQA-xoBYcyyz00tvLkyaG1Wl4Rd5gyoR_mzzBjdiM
# jwt 字段
#  pub exp: i64,
#  pub token: String,


### oauth 
GET {{user_url}}/oauth_login/wechat

### oauth bind
POST {{user_url}}/external/bind
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "config_name": "xx",
    "external_type":"1",
    "external_id":"11",
    "external_name":"11",
    "token_data":"11",
    "token_timeout":111,
    "external_gender":"xx",
    "external_link":"xxx",
    "external_pic":"s"
}


### oauth list
POST {{user_url}}/external/list_data
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "oauth_type": [1]
}



### oauth delete
POST {{user_url}}/external/delete
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "ext_id": 8
}

