
@host_url= http://127.0.0.1:8080
@user_url = {{host_url}}/api/user
@jwt_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidG9rZW4iOiJNVEV0VFVsUlEwdEZRVXhHVkVkUFFrUlZVbGRJV2xaVFdWaFFMVEUyTmpZNE16WXlNVEk9IiwiZXhwIjoxNTE2MjM5MDIyMTF9.lhF6VQmmzFbXRJPOHuH8Ml_C3lwImP2GBPpG1puuKMU

# jwt 字段
#  pub exp: i64,
#  pub token: String,




### ..
POST {{user_url}}/info/set_username
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "name": "xxx"
}



### ..
POST {{user_url}}/info/set_info
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "gender":1,
    "headimg":"aaa.jpg",
    "birthday":"2022-11-11"
}

### ..
POST {{user_url}}/info/set_nikename
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "name": "hi test"
}


### mobile password reset do
POST {{user_url}}/password/set
Content-Type: application/json
Authorization: {{jwt_token}}

{
    "old_password": "xxx",
    "new_password": "123456"
}
