
[workspace]
resolver = "2"
members = [
    "lsys-macros-db",
    "lsys-lib-sms",
    "lsys-lib-area",
    "lsys-lib-jsrun",
    "lsys-core",
    "lsys-kms",
    "lsys-mfa",
    "lsys-rbac",
    "lsys-user",
    "lsys-web",
    "lsys-setting",
    "lsys-logger",
    "lsys-app",
    "lsys-app-sender",
    "lsys-access",
    "lsys-file",
    "lsys-file-manager",
    "examples/*",
]


[profile.dev]
opt-level = 0
incremental = true
lto = false
debug = 1
split-debuginfo = "off"
panic = 'unwind'
codegen-units = 64
rpath = false
overflow-checks = true

[profile.release]
opt-level = 3
lto = true
incremental = false
