[package]
name = "lsys-app-barcode"
version = "0.0.1"
authors = ["liushan <shan.liu@msn.com>"]
edition = "2021"

[dependencies]
tracing = { version = "0.1.*" }
tracing-subscriber = { version = "0.3.*", features = ["env-filter"] }

tokio = { version = "~1.49.0", features = [
    "rt-multi-thread",
    "macros",
    "fs",
    "signal",
] }

axum = { version = "0.7.9", features = ["multipart"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["trace", "cors"] }
http = "1"
bytes = "1"

serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"
serde_urlencoded = "0.7"

tempfile = "3.10.1"

lsys-core = { path = "../../lsys-core", features = ["db", "redis"] }
lsys-logger = { path = "../../lsys-logger" }

lsys-sdk = { path = "../../lsys-sdk" }

image = { version = "0.25.1", default-features = false, features = [
    "png",
    "jpeg",
    "webp",
] }
base64 = "~0.22.0"

sqlx = { version = "~0.8.6", features = ["mysql", "runtime-tokio-native-tls"] }

async-trait = "~0.1.*"
rxing = { version = "0.7.1", default-features = false, features = [
    "image",
    "svg_read",
] }
sha2 = "~0.10.8"
md5 = "~0.8.0"
