
@host_url= http://127.0.0.1:8080
@user_url = {{host_url}}/api/user
@jwt_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidG9rZW4iOiJNVGN0VGtSWVNGbE5Wa0ZEVVVWVFRFZEpWMXBRVDBaTFVsUlZMVEUyTnpJNU1UQTNNalU9IiwiZXhwIjoxNTE2MjM5MDIyMTF9._p2A33VfAi8woUtKeyOnxhE_mNU9vKoeMsh70Kz6ctU

# jwt 字段
#  pub exp: i64,
#  pub token: String,


### OPTIONS
OPTIONS  {{user_url}}/aaaa


### reg
POST {{user_url}}/signup/name
Content-Type: application/json

{
    "name": "aaaaa",
    "password": "000000"
}


### reg mail cpatcha
GET  {{host_url}}/captcha/reg-email/shan.liu@msn.com

### reg mail code
POST {{user_url}}/signup/email-code
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
     "captcha":  {
        "code":"gDHMb",
        "key":"shan.liu@msn.com"
    }
}

### reg mail do

POST {{user_url}}/signup/email
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "code": "810249",
    "password":"123456"
}



### reg sms cpatcha
GET  {{host_url}}/captcha/reg-sms/8613800138000


### reg sms code
POST {{user_url}}/signup/sms-code
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code": "86",
    "captcha":  {
        "code":"gDHMb",
        "key":"8613800138000"
    }
}

### reg sms do
POST {{user_url}}/signup/sms
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code": "86",
    "code":"475839",
    "password":"123456"
}


### reg sms cpatcha
GET  {{host_url}}/captcha/login/aaamm

### login
POST {{user_url}}/login/name
Content-Type: application/json

{
    "name": "aaaaa",
    "password": "000000",
    "captcha":  {
        "code":"9ea",
        "key":"aaamm"
    }
}

### reg sms cpatcha
GET  {{host_url}}/captcha/login/13800138000[86]



### reg sms cpatcha
GET  {{host_url}}/captcha/login/shan.liu@msn.com

### login email password
POST {{user_url}}/login/email
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "password": "bb1111",
     "captcha":  {
        "code":"gDHMb",
        "key":"shan.liu@msn.com"
    }
}

### reg sms cpatcha
GET  {{host_url}}/captcha/login/13800138000[86]

### login sms password
POST {{user_url}}/login/sms
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code": "86",
    "password": "987654",
    "captcha":  {
        "code":"gDHMb",
        "key":"13800138000[86]"
    }
}





### login mail cpatcha
GET  {{host_url}}/captcha/login-sms/8613800138000

### login mail code
POST {{user_url}}/login/sms-send-code
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code": "86",
    "captcha":  {
        "code":"gDHMb",
        "key":"8613800138000"
    }
}


### login sms code
POST {{user_url}}/login/sms-code
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code": "86",
    "code": "bb",
    "captcha":null
}



### login mail cpatcha
GET  {{host_url}}/captcha/login-email/shan.liu@msn.com

### login mail code
POST {{user_url}}/login/email-send-code
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "captcha":  {
        "code":"gDHMb",
        "key":"shan.liu@msn.com"
    }
}


### login email password
POST {{user_url}}/login/email-code
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "code": "bb",
    "captcha":null
}

### login data
POST {{user_url}}/login_data
Content-Type: application/json
Authorization: {{jwt_token}}

{
    "reload_auth":true,
    "auth":true,
    "user":true,
    "name":true,
    "info":true,
   // "external":true,
    //"email":[2],
    //"mobile":[2],
    "address":true
}

### login data
POST {{user_url}}/login_history
Content-Type: application/json
Authorization: {{jwt_token}}

{
    "login_type":null,
    "is_login":1,
    "page":{
        "page": 1,
        "limit": 10
    }
}




### logout
GET {{user_url}}/logout
Authorization: {{jwt_token}}


### email password reset cpatcha
GET  {{host_url}}/captcha/reset-password-send-mail/shan.liu@msn.com

### email password reset
POST {{user_url}}/password_reset/email_code
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "captcha": {
        "code":"gDHMb",
        "key":"shan.liu@msn.com"
    }
}


### email password reset do
POST {{user_url}}/password_reset/email
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "code": "357028",
    "new_password": "bb1111"
}



### mobile password reset cpatcha
GET  {{host_url}}/captcha/reset-password-send-sms/8613800138000

### mobile password_reset
POST {{user_url}}/password_reset/mobile_code
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code":"86",
    "captcha": {
        "code":"xxx",
        "key":"8613800138000"
    }
}


### mobile password reset do
POST {{user_url}}/password_reset/mobile
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code":"86",
    "code": "615432",
    "new_password": "987654"
}



//OAUTH登录....
POST {{host_url}}/external_login_url
Content-Type: application/json

{
    "login_type": "wechat",
    "login_callback":"http://xxxx.com",
    "login_state": "615432"
}

//扫码登录检测是否已经完成登录
POST {{host_url}}/external_state_check
Content-Type: application/json

{
    "login_type": "wechat",
    "login_state": "615432"
}

//app扫码后登陆回写数据
POST {{host_url}}/external_state_callback
Content-Type: application/json

{
    "login_type": "wechat",
    "code": "xxxxxxxxxxx",
    "callback_state": "xxxxxxxxxxx",
}