
@host_url= http://127.0.0.1:8080
@url = {{host_url}}/api/sender
@jwt_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidG9rZW4iOiJNVGN0VDBaQ1VFbFJXa0ZPV0ZkRFNGVkxVMHBXVWsxRldWUkVMVEUyTnpZMk1UazFNalUiLCJleHAiOjE1MTYyMzkwMjIxfQ.q8rEUYVWIyAN5TsdJ1BH9C4zkSGWahGbMGEJTw5fTFs

###### rbac ########


### 添加短信配置
POST {{url}}/smser/config_add
Authorization: {{jwt_token}}

{
    "app_id": 1,
    "priority": 1,
    "config_type": 3,
    "config_data":"xxx"
}


### 删除短信配置
POST {{url}}/smser/config_del
Authorization: {{jwt_token}}

{
   "config_id":1
}

### 短信配置列表
POST {{url}}/smser/config_list
Authorization: {{jwt_token}}

{
   "app_id":1
}

### 阿里短信配置列表
POST {{url}}/smser/ali_config_list
Authorization: {{jwt_token}}

{
   "id":null
   "full_data":true
}


###  阿里短信配置添加
POST {{url}}/smser/ali_config_add
Authorization: {{jwt_token}}

{
    "name": "bbbb",
    "access_id": "ssss",
    "access_secret":"cccc"
}


###  阿里短信配置删除
POST {{url}}/smser/ali_config_del
Authorization: {{jwt_token}}

{
    "id":1,
}



###  阿里短信配置编辑
POST {{url}}/smser/ali_config_edit
Authorization: {{jwt_token}}

{
    "id": 29,
    "name": "faadsf",
    "access_id": "adfad",
    "access_secret":"asdfa"
}


###  阿里短信配置关联短信发送
POST {{url}}/smser/ali_app_config_add
Authorization: {{jwt_token}}

{
    "app_id": 1,
    "ali_config_id":29,
    "sms_tpl": "adfad",
    "aliyun_sms_tpl": "adfad",
    "aliyun_sign_name": "adfad"
}



### 阿里短信配置关联短信发送删除
POST {{url}}/smser/ali_app_config_del
Authorization: {{jwt_token}}

{
    "app_config_id": 29
}