
@host_url=  http://175.178.90.181:8000
@user_url = {{host_url}}/api/user
@jwt_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzA1OTkyODksInRva2VuIjoiTWpjdFVFVlBXRVpUVjBSTlNGVktXazVKUWtOTFVWbEJURkpXTFRFMk56QTFPVGt5T0RrPSIsImlhdCI6MTY3MDUxMjg5OH0.RddjV0mxC_S6Lem6i5ge6jRmjrZMQ4iJxp_0AqpKM7w
###### rbac ########

### 可配置的权限列表
POST {{user_url}}/res/all
Authorization: {{jwt_token}}

{
    "global_res":false
}

### 用户已配置资源列表
POST {{user_url}}/res/list_data
Authorization: {{jwt_token}}

{
   // "user_id":39,
   // "res_ids":[51],
   // "tags_filter":[""],
    "tags":true,
    "ops":true,
    "page":{
        "page": 1,
        "limit": 10
    }
}


### 资源所有TAG
POST {{user_url}}/res/tags
Authorization: {{jwt_token}}

{
  //  "user_id":39
}


### add资源列表
POST {{user_url}}/res/add
Authorization: {{jwt_token}}

{
   // "user_id":39,
    "key":"hhh21ee8",
    "name":"xx21ddd",
    "ops":[{
        "name":"xxx",
        "key":"xxx"
    },
    {
        "name":"xxx1",
        "key":"xxx1"
    }],
    "tags":[
        "xxx","uuu"
    ]
}

### edit资源
POST {{user_url}}/res/edit
Authorization: {{jwt_token}}

{
    "res_id":9,
    "key":"hhh",
    "name":"xx",
    "ops":[{
        "name":"xxx",
        "key":"xxx"
    }],
    "tags":[
        "xxx"
    ]
}


### 删除资源
POST {{user_url}}/res/delete
Authorization: {{jwt_token}}

{
   "res_id":9
}

### 角色 add
POST {{user_url}}/role/add
Authorization: {{jwt_token}}

{
 //   "user_id":15,
    "name":"test10031",
    "user_range":3,
    "role_op_range":1,
    "priority":10,
    "relation_key":"test-key",
    "tags":["test_tag1"],
   "role_user":[
        {
           "user_id":110,
            "timeout": 1000
       }
   ],
    "role_ops":[
        {
            "op_id":6,
            "op_positivity": 1
        },
         {
            "op_id":7,
            "op_positivity": 1
        }
    ]
}


### 角色 edit
POST {{user_url}}/role/edit
Authorization: {{jwt_token}}

{
    "role_id":768719,
    "name":"xxpp21",
    "user_range":3,
    "role_op_range":1,
    "priority":10,
    "relation_key":"xxx",
    "tags":["xx12"],
    "role_ops":[
        {
            "op_id":8,
            "op_positivity": 1
        },
        {
            "op_id":6,
            "op_positivity": 1
        }
    ]
  
}

  


### 角色 delete
POST {{user_url}}/role/delete
Authorization: {{jwt_token}}

{
    "role_id":39
}



### 角色 add_user
POST {{user_url}}/role/add_user
Authorization: {{jwt_token}}

{
    "role_id":768719,
    "user_vec":[
        {
            "user_id":6,
            "timeout": 1000
        }
    ]
}


### 角色 delete_user
POST {{user_url}}/role/delete_user
Authorization: {{jwt_token}}

{
    "role_id":768719,
    "user_vec":[
      4,5
    ]
}




### 角色 list_user
POST {{user_url}}/role/list_user
Authorization: {{jwt_token}}

{
    "count_num":true,
   "role_ids":[768719],
     "page":{
        "page": 1,
        "limit": 2
    }
}


### 角色 list_data
POST {{user_url}}/role/list_data
Authorization: {{jwt_token}}

{
 //   "user_id":1,
//     "role_ids":[768719],
    //  "tags_filter":["xx121"],
      "tags":true,
      "ops":2,
      "user_data":true,
     "page":{
        "page": 1,
        "limit": 10
    },
    "count_num":true,
    "user_data_page":{
        "page": 1,
        "limit": 10
    }
}


### 角色 tags
POST {{user_url}}/role/tags
Authorization: {{jwt_token}}

{
   //"user_id":1
}


### 权限校验
POST {{user_url}}/access/check
Authorization: {{jwt_token}}

{
    "relation_key":[
       {
        "role_key":"firend",
        "user_id":1
       }
    ],
    "check_res":[
       [
         {
        "res":"hhh",
        "user_id":0,
        "ops":["xxx"]
       }
       ]
    ]
}


### 菜单过滤
POST {{user_url}}/access/menu
Authorization: {{jwt_token}}

{
    "relation_key":[
       {
        "role_key":"firend",
        "user_id":1
       }
    ],
    "check_res":[
        {
            "name":"xxx",
            "access_check":[
                [
                    {
                    "res":"user",
                    "user_id":0,
                    "ops":["add"]
                    }
                ]
            ]
        }
    ]
}
