# @import ./rest_user_login.http
# @ref name_login

###
POST /api/area/list
Content-Type: application/json

{
    "code": ""
}


###
POST /api/area/search
Content-Type: application/json

{
    "key_word": "meizhou"
}


###
POST /api/area/related
Content-Type: application/json

{
    "code": "4414"
}


###
POST /api/area/find
Content-Type: application/json

{
    "code": "1110"
}


###
POST /api/area/geo
Content-Type: application/json

{
    "lat": 26.61474, 
    "lng": 114.13548
}


###
POST /api/user/address/add
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "code": "111000",
    "info": "广东深圳龙岗",
    "detail": "布吉xxx",
    "name": "xxx",
    "mobile":"13500135000"
}


###
POST /api/user/address/list_data
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{}


###
POST /api/user/address/delete
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "address_id": 4
}