# @import ./rest_user_login.http
# @ref name_login


###### rbac ########

### 可配置的权限列表
POST /api/user/res/all
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
  //  "global_res":true
}

### 用户已配置资源列表
POST /api/user/res/list_data
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "user_id":1,
   // "res_ids":[51],
   // "tags_filter":[""],
    "tags":true,
    "ops":true,
    "page":{
        "page": 1,
        "limit": 10
    }
}


### 资源所有TAG
POST /api/user/res/tags
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
  //  "user_id":39
}


### add资源列表
POST /api/user/res/add
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   // "user_id":39,
    "key":"hhh21",
    "name":"xx21",
    "ops":[{
        "name":"xxx",
        "key":"xxx"
    },
    {
        "name":"xxx1",
        "key":"xxx1"
    }],
    "tags":[
        "xxx","uuu"
    ]
}

### edit资源
POST /api/user/res/edit
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "res_id":9,
    "key":"hhh",
    "name":"xx",
    "ops":[{
        "name":"xxx",
        "key":"xxx"
    }],
    "tags":[
        "xxx"
    ]
}


### 删除资源
POST /api/user/res/delete
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   "res_id":9
}

### 角色 add
POST /api/user/role/add
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
 //   "user_id":15,
    "name":"test10031",
    "user_range":3,
    "role_op_range":1,
    "priority":10,
    "relation_key":"test-key",
    "tags":["test_tag1"],
   "role_user":[
        {
           "user_id":110,
            "timeout": 1000
       }
   ],
    "role_ops":[
        {
            "op_id":9,
            "op_positivity": 1
        },
         {
            "op_id":8,
            "op_positivity": 1
        }
    ]
}


### 角色 edit
POST /api/user/role/edit
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "role_id":768719,
    "name":"xxpp21",
    "user_range":3,
    "role_op_range":1,
    "priority":10,
    "relation_key":"xxx",
    "tags":["xx12"],
    "role_ops":[
        {
            "op_id":8,
            "op_positivity": 1
        },
        {
            "op_id":6,
            "op_positivity": 1
        }
    ]
  
}

  


### 角色 delete
POST /api/user/role/delete
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "role_id":39
}



### 角色 add_user
POST /api/user/role/add_user
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "role_id":768719,
    "user_vec":[
        {
            "user_id":6,
            "timeout": 1000
        }
    ]
}


### 角色 delete_user
POST /api/user/role/delete_user
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "role_id":768719,
    "user_vec":[
      4,5
    ]
}




### 角色 list_user
POST /api/user/role/list_user
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "count_num":true,
   "role_ids":[768719],
     "page":{
        "page": 1,
        "limit": 2
    }
}

### 角色选项
POST /api/user/role/options
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
}


### 角色列表
POST /api/user/role/list_data
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
 //   "user_id":1,
//     "role_ids":[768719],
    //  "tags_filter":["xx121"],
      "tags":true,
      "ops":true,
      "user_data":true,
     "page":{
        "page": 1,
        "limit": 10
    },
    "count_num":true,
    "user_data_page":{
        "page": 1,
        "limit": 10
    }
}


### 角色 tags
POST /api/user/role/tags
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   //"user_id":1
}

### 权限校验
# name 参考 server\lsys-web\src\handler\common\rbac\mod.rs access_check
POST /api/user/access/check
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "name":"admin-sms-config",
    "data":null,
    "relation":[{
         "role_key":"firend",
         "user_id":1
    }]
}


### 菜单过滤
POST /api/user/access/menu
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "check_res":[
        {
            "name":"admin-sms-config",
            "data":null,
            "relation":[{
                "role_key":"firend",
                "user_id":1
            }]
        }
    ]
}
