# @import ./rest_user_login.http
# @ref name_login



### 添加
# @name app_add
POST /api/app/add
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}


{
    "user_id": 17,
    "name": "ddffddd",
    "client_id": "ddffddd"
}

### 审核
# @ref app_add
POST /api/app/confirm
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   "app_id": {{app_add.response.id}}
}


### 查看秘钥
# @ref app_add
POST /api/app/view_secret
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "app_id": {{app_add.response.id}}
}



### 重置KEY
# @ref app_add
POST /api/app/reset_secret
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   "app_id": {{app_add.response.id}}
}

### 列表
POST /api/app/list
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}


{
    "count_num": true,
    "user_id":17
    //"app_id":[1],
    //"status":[1],
    //"client_ids": ["111"],
}








### 设置可访问应用的用户
POST /api/app/set_sub_user
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   "app_id": 2,
   "user_id":17,
   "used":true
}

### 列出可访问用户
POST /api/app/list_sub_user
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   "app_id": 17,
   //"user_id":1,
   "count_num":true
}



### 列出某应用的子应用
POST /api/app/list_sub_app
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   "app_id": 17,
   //"user_id":1,
   "count_num":true
}




### 列出指定应用已关联的父应用
POST /api/app/list_parent_app
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   "app_id": 82,
   //"is_set":null,
   "count_num":true
}




### 指定应用关联指定父应用
POST /api/app/set_parent_app
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   "app_id": 1,
   "parent_app_id":2,
   "sub_secret":"xxxx"
}


### 移除指定应用关联指定父应用
POST /api/app/del_parent_app
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
   "app_id": 3,
   "parent_app_id":4
}

