# @import ./rest_user_login.http
# @ref name_login



### login data
POST /api/user/login_data
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "reload_auth":true,
    "auth":true,
    "user":true,
    "name":true,
    "info":true,
   // "external":true,
    //"email":[2],
    //"mobile":[2],
    "address":true
}

### login history
POST /api/user/login_history
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "login_type":null,
    "is_login":1,
    "page":{
        "page": 1,
        "limit": 10
    }
}


### logout
GET /logout
Authorization:Bearer {{name_login.response.jwt}}


### ..
POST /api/user/info/set_username
Content-Type:application/json
Authorization:Bearer {{name_login.response.jwt}}

{
    "name": "xxx"
}



### ..
POST /api/user/info/set_info
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "gender":1,
    "headimg":"aaa.jpg",
    "birthday":"2022-11-11"
}

### ..
POST /api/user/info/set_nikename
Authorization: {{jwt_token}}
Content-Type: application/json

{
    "name": "hi test"
}


### mobile password reset do
POST /api/user/password/set
Content-Type: application/json
Authorization: {{jwt_token}}

{
    "old_password": "xxx",
    "new_password": "123456"
}

### 用户操作日志
POST /api/user/logs/change
Content-Type: application/json
Authorization: {{jwt_token}}

{
    
}





