
### OPTIONS
OPTIONS  /api/user/


### reg
POST /api/user/signup/name
Content-Type: application/json

{
    "name": "aaaaa",
    "password": "000000"
}


### reg mail cpatcha
GET  /captcha/reg-email/shan.liu@msn.com

### reg mail code
POST /api/user/signup/email-code
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
     "captcha":  {
        "code":"c9e",
        "key":"shan.liu@msn.com"
    }
}

### reg mail do

POST /api/user/signup/email
Content-Type: application/json

{
    "nikename":"SHAN",
    "email": "shan.liu@msn.com",
    "code": "810249",
    "password":"123456"
}



### reg sms cpatcha
GET  /captcha/reg-sms/8613800138000


### reg sms code
POST /api/user/signup/sms-code
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code": "86",
    "captcha":  {
        "code":"TpS",
        "key":"8613800138000"
    }
}

### reg sms do
POST /api/user/signup/sms
Content-Type: application/json

{
    "nikename":"SHAN",
    "mobile": "13800138000",
    "area_code": "86",
    "code":"475839",
    "password":"123456"
}


### reg sms cpatcha
GET  /captcha/login/aaamm

### login
# @name name_login
POST /api/user/login/name
Content-Type: application/json
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8

{
    "name": "aaaaa",
    "password": "000000",
    "captcha":  {
        "code":"9ea",
        "key":"aaamm"
    }
}

### reg sms cpatcha
GET  /captcha/login/13800138000[86]



### reg sms cpatcha
GET  /captcha/login/shan.liu@msn.com

### login email password
POST /api/user/login/email
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "password": "bb1111",
     "captcha":  {
        "code":"32e",
        "key":"shan.liu@msn.com"
    }
}

### reg sms cpatcha
GET  /captcha/login/13800138000[86]

### login sms password
POST /api/user/login/sms
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code": "86",
    "password": "987654",
    "captcha":  {
        "code":"w5q",
        "key":"13800138000[86]"
    }
}





### login mail cpatcha
GET  /captcha/login-sms/8613800138000

### login mail code
POST /api/user/login/sms-send-code
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code": "86",
    "captcha":  {
        "code":"lbG",
        "key":"8613800138000"
    }
}


### login sms code
POST /api/user/login/sms-code
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code": "86",
    "code": "bb",
    "captcha":null
}



### login mail cpatcha
GET  /captcha/login-email/shan.liu@msn.com

### login mail code
POST /api/user/login/email-send-code
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "captcha":  {
        "code":"gDHMb",
        "key":"shan.liu@msn.com"
    }
}


### login email password
POST /api/user/login/email-code
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "code": "bb",
    "captcha":null
}



### email password reset cpatcha
GET  /captcha/reset-password-send-mail/shan.liu@msn.com

### email password reset
POST /api/user/password_reset/email_code
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "captcha": {
        "code":"gDHMb",
        "key":"shan.liu@msn.com"
    }
}


### email password reset do
POST /api/user/password_reset/email
Content-Type: application/json

{
    "email": "shan.liu@msn.com",
    "code": "357028",
    "new_password": "bb1111"
}



### mobile password reset cpatcha
GET  /captcha/reset-password-send-sms/8613800138000

### mobile password_reset
POST /api/user/password_reset/mobile_code
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code":"86",
    "captcha": {
        "code":"xxx",
        "key":"8613800138000"
    }
}


### mobile password reset do
POST /api/user/password_reset/mobile
Content-Type: application/json

{
    "mobile": "13800138000",
    "area_code":"86",
    "code": "615432",
    "new_password": "987654"
}



//OAUTH登录....
POST /api/user/external_login_url
Content-Type: application/json

{
    "login_type": "wechat",
    "login_callback":"http://xxxx.com",
    "login_state": "615432"
}

//扫码登录检测是否已经完成登录
POST /api/user/external_state_check
Content-Type: application/json

{
    "login_type": "wechat",
    "login_state": "615432"
}

//app扫码后登陆回写数据
POST /api/user/external_state_callback
Content-Type: application/json

{
    "login_type": "wechat",
    "code": "xxxxxxxxxxx",
    "callback_state": "xxxxxxxxxxx"
}