[package]
name = "lsys-mfa"
version = "0.1.0"
edition = "2024"

[dependencies]
lsys-core = { path = "../lsys-core", features = ["db-mysql"] }

serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"

tokio = { version = "~1.49.0" }
sqlx = { version = "~0.8.6", features = ["mysql", "runtime-tokio-native-tls"] }

async-trait = "~0.1.*"

# TOTP
base32 = "0.5"
hmac = "0.12"
sha1 = "0.10"

[features]
default = []
