name: check lsys ui

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ui/**/*'
      - '!ui/**/*.md'
      - '!ui/**/*.MD'
      - '!ui/**/*.cmd'
      - '!ui/**/.gitignore'
      - '.github/workflows/check_ui.yml'

jobs:
  ui_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Build ui
      working-directory: ./ui
      run: |
        pnpm install
        pnpm build
